#include <stdio.h>

#define MAX 50


int buscaBinaria(int v[], int n, int valor) {
    int esq = 0, dir = n - 1, meio;
        while (esq <= dir) {
                meio = (esq + dir) / 2;
                        if (v[meio] == valor)
                                    return meio;
                                            else if (valor < v[meio])
                                                        dir = meio - 1;
                                                                else
                                                                            esq = meio + 1;
                                                                                }
                                                                                    return -1; // não encontrei :(
                                                                                    }

                
                                                                                    int inserirOrdenado(int v[], int n, int valor) {
                                                                                        if (n >= MAX) return n;

                                                                                            int i = n - 1;
                                                                                                while (i >= 0 && v[i] > valor) {
                                                                                                        v[i + 1] = v[i];
                                                                                                                i--;
                                                                                                                    }
                                                                                                                        v[i + 1] = valor;
                                                                                                                            return n + 1;
                                                                                                                            }

                                                                                                                            
                                                                                                                            int remover(int v[], int n, int valor) {
                                                                                                                                int pos = buscaBinaria(v, n, valor);
                                                                                                                                    if (pos == -1) return n; // não encontreeeii :(

                                                                                                                                        for (int i = pos; i < n - 1; i++) {
                                                                                                                                                v[i] = v[i + 1];
                                                                                                                                                    }
                                                                                                                                                        return n - 1;
                                                                                                                                                        }

                                                                                                                                                        
                                                                                                                                                        void imprimir(int v[], int n) {
                                                                                                                                                            printf("Vetor: ");
                                                                                                                                                                for (int i = 0; i < n; i++) {
                                                                                                                                                                        printf("%d ", v[i]);
                                                                                                                                                                            }
                                                                                                                                                                                printf("\n");
                                                                                                                                                                                }

                                                                                                                                                                                int main() {
                                                                                                                                                                                    int vetor[MAX], n, valor, opcao, pos;

                                                                                                                                                                                        
                                                                                                                                                                                            do {
                                                                                                                                                                                                    printf("Digite o tamanho do vetor (3 a 50): ");
                                                                                                                                                                                                            scanf("%d", &n);
                                                                                                                                                                                                                } while (n < 3 || n > 50);

                                                                                                                                                                                                                    
                                                                                                                                                                                                                        printf("Digite %d valores inteiros:\n", n);
                                                                                                                                                                                                                            int atual = 0;
                                                                                                                                                                                                                                for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                        scanf("%d", &valor);
                                                                                                                                                                                                                                                atual = inserirOrdenado(vetor, atual, valor);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            do {
                                                                                                                                                                                                                                                                    printf("\nMenu:\n");
                                                                                                                                                                                                                                                                            printf("1 - Imprimir vetor\n");
                                                                                                                                                                                                                                                                                    printf("2 - Consultar valor\n");
                                                                                                                                                                                                                                                                                            printf("3 - Remover valor\n");
                                                                                                                                                                                                                                                                                                    printf("4 - Inserir valor\n");
                                                                                                                                                                                                                                                                                                            printf("0 - Sair\n");
                                                                                                                                                                                                                                                                                                                    printf("Opcao: ");
                                                                                                                                                                                                                                                                                                                            scanf("%d", &opcao);

                                                                                                                                                                                                                                                                                                                                    if (opcao == 1) {
                                                                                                                                                                                                                                                                                                                                                imprimir(vetor, atual);
                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                else if (opcao == 2) {
                                                                                                                                                                                                                                                                                                                                                                            printf("Digite valor para consultar: ");
                                                                                                                                                                                                                                                                                                                                                                                        scanf("%d", &valor);
                                                                                                                                                                                                                                                                                                                                                                                                    pos = buscaBinaria(vetor, atual, valor);
                                                                                                                                                                                                                                                                                                                                                                                                                printf("Posicao: %d\n", pos);
                                                                                                                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                                                                                                                                else if (opcao == 3) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Digite valor para remover: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                        scanf("%d", &valor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    atual = remover(vetor, atual, valor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (opcao == 4) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (atual < MAX) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Digite valor para inserir: ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                scanf("%d", &valor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                atual = inserirOrdenado(vetor, atual, valor);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Vetor cheio! Nao eh possivel inserir.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else if (opcao == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Saindo...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Opcao invalida!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } while (opcao != 0);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                